[package]
name = "axum"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
deserr = { path = "../../", features = ["axum"] }
axum = { version = "0.8.4", features = ["json", "macros"] }
tokio = { version = "1.47", features = ["full"] }
serde = { version = "1.0.223", features = ["derive"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
